#main:
#  - name: Blog2
#    identifier: blog2
#    pre: '<i class="fas fa-fw fa-blog me-1"></i>'

#  - name: Documentations
#    identifier: documentations
#    url: https://hbs.razonyang.com/v1/en/docs/
#    params:
#      icon: '<i class="fas fa-fw fa-book"></i>'
